[functions]
  directory = "functions"

# The following redirect is intended for use with most SPAs that handle
# routing internally.
[[redirects]]
  from = "/data/bounce"
  to = "/.netlify/functions/bounce"
  status = 200